import Navbar from "@/components/Navbar";
import { authStore } from "@/store";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  const user = authStore((state: any) => state.user);

  return (
    <>
      <Head>
        <title>Strapi Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 maximum-scale=1"
        />
        <link
          rel="icon"
          href="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1f47b.svg"
        />
      </Head>
      <Navbar user={user} />
      <Component {...pageProps} />
    </>
  );
}
