import Head from "next/head";
import { Inter } from "@next/font/google";
import React from "react";
import { authStore } from "@/store";
import Login from "@/components/Forms/Login";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const user = authStore((state: any) => state.user);
  const [isLogin, setIsLogin] = React.useState<Boolean>(true);

  React.useLayoutEffect(() => {
    if (user && user?.username) {
      setIsLogin(true);
    } else {
      setIsLogin(false);
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Strapi Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1" />
        <link rel="icon" href="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1f47b.svg" />
      </Head>
      <main>{isLogin ? <h1>Welcome</h1> : <Login />}</main>
    </>
  );
}
